### ISSUE TITLE
Historic Template

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org#118]
We need to create plan on how to move forward with this. We are just pulling data from the Historic DB, and it does not truly fit at this time.

Suggestions (per Jason):

- Remove them, add them back as an enhancement. Would need to leave current order form on page.
or
- One Card for all historic collection till individual collections can be added.

**Comment by adambreznicky** [comment]
as per out discussion yesterday:
- updated the template to move coverage map on new tab to be consistent with other template
- updated metadata to use source instead of agency. this was a bug that got missed when migrating from 'agency' to 'source' a few weeks back
- updated model to include additional collection agency details from tnris.org rdc page. added these to both the metadata component and a new 'about' chunk on the historical template
- added a standard description about ordering historic imagery
- added citation component for consistency
- added image carousel for template consistency. includes an additional 'sample' image for the 7 collection agencies with details on tnris.org

resolved 746c89be9a6ea38889de7498bdec6bb760228eab
