### ISSUE TITLE
metadata component update

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/data.tnris.org#33]
remove tags, known issues, recommended use, and coverage extent
drop data types?
resource types relabeled to "download formats"?
move category last

adjust list label to value ratio. currently is 50/50. label should be closer to 1/5 and value 4/5

acquisition year to title?

**Comment by jwhaney** [comment]
- moved acquisition year to title for all templates, moved to end of title for historical existing year.
- tags, known, issues, rec use, coverage extent removed
- changed metadata list spacing
- no sass for 50/50 in metadata component due to change to mdc-list-item__primary-text and __secondary_text (stacked)
- resource types relabeled to download formats in metadata
- category moved to last in metadata

resolved via commits: ed759ed5bbc5c593f1ed61bc1be0c4d95ae20742, 449aa15d52d81023e30926d9b0e2a9e1eaffa3cd
