### ISSUE TITLE
Social Media Sharing Buttons

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#7]
What is the case for social media shares on data catalog filtering options?

I don't see them as necessary.

**Comment by adambreznicky** [comment]
this is a general share option of the catalog itself rather than a specific dataset. this provides a user the option to share the entire site with any filtered view they have set. due to the numerous filtering options/methods, this enables a user to share their view with others easily opposed to having to dictate what options they chose in order to list the datasets they are seeing.
for example, if one wanted to tweet our lidar data to say "Wow, look at all this free lidar data! https://data.tnris.org/catalog/%7B%22filters%22%3A%7B%22category%22%3A[%22Lidar%22]%7D%7D", these share buttons give them the one-click option to do so.
