### ISSUE TITLE
Add Caption Field for Images

### ISSUE THREAD

**Issue by christoball** [TNRIS/data.tnris.org#90]
Add the option of a caption field. This could also function as an alt tag.

**Comment by jwhaney** [comment]
just a heads up on where we stand with this: 

we will plan on adding the change to the model eventually where a text blurb (prob max character of something relatively small) can be associated with each image uploaded to a collection which will then be reflected on the front end in the image carousel. however, this is not a high priority right now because even if this was up and running right now, it still requires content managers to enter a text blurb for every image we currently have on the site, which is a lot. 

the react-responsive-carousel currently supports a 'legend" class for each image which would make it very simple to populate with the text content.
![image-carousel-legend.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b69c10b3c8a4500139e198f/125516c66e82c728ace21e0d46e1999b2487ceaa8efbb056b758fcd9254320762700e1673295f127b54778154d555ca912595e43f5aa8e7ff7b16d78835c0ae587685e76ce3843bea4905dee5fee7fd616cfe3fe9846d2e9352fe68e8a4f3c18041f8cfc5f34a28b06.gif)

the black and hover to make transparency disappear can of course be changed. this is just the default carousel functionality.

**Comment by adambreznicky** [comment]
default carousel functionality is def the way to go.
i added the caption field to the model and it appears in the admin console as expected now. max character limit of 255. this can be adjusted at any time. it's probably too large right now but we aren't using them so its irrelevant. closing the issue and we can return after they get populated.
resolved 1a36638eaed101eff0a59034d3c3bfb79b1174b5
